### ISSUE TITLE
[betaFinalTesting] 베타 출시 전 최종 점검

### ISSUE THREAD

**Issue by woorim960** [wooahan-agile/idu-market-server#217]
## 목적
> 베타 출시 전 최종적으로 수행해야 할 이슈 정리

## 구현 기능
* Back-End
- [x] 판매완료 시 status 3으로 변경 api 구현 #216
- [x] CORS
- [x] 비번 변경시 해시 암호화 적용 #215 
- [x] 비번 찾기 URL이 지정된 환경 변수 변경 #209 
- [x] MariaDB 데이터 자동 백업 되도록 구현 #187 
- [x] Docker 컨테이너 내부의 로그 파일이 EC2 로컬에 저장되도록 구현 #186 
- [x] insertId 필요한 부분에서만 사용했는지 점검
- [x] 모든 게시판 작성자를 응답할 때 isAdmin을 응답해주기
- [x] 백엔드 서버의 로그 저장 시간이 한국 시간으로 저장되도록 변경 #231 

* Front-End
- [x] 알림 UI 구현
- [x] 알림 데이터 서버에서 가져오기 구현
- [x] 구매 완료 시 거래 완료 버튼 제거
- [x] Console 출력 제거
- [x] 관리자 계정 색 빨간색 변경
- [x] 공지 & 자유게시판 쓰기에서 이미지 업로더 추가
- [x] 로그인 안한채로 게시글 작성할 경우 로그인 화면으로 이동하도록 구현 
   -> 지금은 "An unexpected error has occurred." 라고 출력됨
- [x] 자유 & 공지 게시판에 (게시글 생성할 때) 업로드한 이미지가 보이도록 구현
   -> 게시글을 수정할 떄 업로드한 이미지는 정상적으로 출력됨.
- [x] 마켓 게시판에서 남이 올린 게시글에 "판매중" , "예약중" , "거래완료" 상태가 보이도록 수정
   -> 본인 게시글에서만 확인이 가능한 상태임
   -> 남의 게시글을 보고 현재 판매가 완료된 것인지 확인할 수 있어야함.
- [x] 모든 게시판을 생성 * 삭제한 후 메인 조회 화면으로 이동하면 곧바로 조회되지 않음
   -> 새로고침 해야 등장함.

* Project
- [x] v1.0.0 배포.
- [x] 깃허브 태그명 붙이기
- [x] 기존 데이터 삭제
- [x] 공지 적어놓기
   -> 공지 게시판과 메인 공지 변경
- [x] 가이드 영상 제작
- [x] 중고 물품 하나씩 업로드 해놓기
- [x] 관리자용 계정 5개 만들어 놓기
- [x] SNS 홍보 공지글 작성

* 출시 테스트
- [x] 웹 프로덕트 버전을 이용해보면서 발생하는 이슈 정리.

* 출시 이후
- [ ] 로그 메세지 상세하게 변경
- [x] 리드미 작성

* 보류
- [ ] 거래완료 상태 클릭시 "거래완료"버튼이 나오는 것이 아니라 바로 거래완료 선택 화면으로 이동하도록 구현
- [ ] 마켓 게시판의 전체조회 글마다 조회수가 반영이 안됨
   -> 상세화면으로 이동하면 반영된 조회수는 정상 조회된다.
   -> 전체 조회에서만 변함없는 조회수가 고정적으로 조회됨
